name: Install Taskmates

on:
  workflow_call:
    inputs:
      taskmates-version:
        required: false
        type: string
        default: 'main'
        description: 'Taskmates version to install'
      python-version:
        required: false
        type: string
        default: '3.11'
        description: 'Python version to use for installing Taskmates'

jobs:
  install-taskmates:
    runs-on: ubuntu-latest
    steps:
      - name: Install Taskmates
        uses: taskmates/install-taskmates@main
        with:
          version: ${{ inputs.taskmates-version }}
          github_token: ${{ secrets.github_token }}
          python-version: ${{ inputs.python-version }}

      - name: Verify Taskmates Installation
        run: taskmates --version
